[21-Nov-2023 16:30:19 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:30:19 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('favicon.ico')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 16:35:56 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:35:56 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('favicon.ico')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 16:36:28 Europe/Berlin] Uncaught exception: 'Exception' with message 'Controller class App\Controllers\Products not found'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('products/123/ne...')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 128
[21-Nov-2023 16:37:10 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('products')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 16:44:30 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('products')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 16:44:38 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('products')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 16:44:59 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('products')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 16:45:06 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:45:10 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:45:17 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:47:07 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:47:08 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
[21-Nov-2023 16:47:20 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 17:06:13 Europe/Berlin] Uncaught exception: 'Exception' with message 'No router matched'
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts')
#1 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php' on line 132
[21-Nov-2023 17:06:15 Europe/Berlin] Uncaught exception: 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user 'mvc'@'localhost' to database 'mvc''
Stack trace: #0 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php(30): PDO->__construct('mysql:host=loca...', 'mvc', Object(SensitiveParameterValue))
#1 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Models\Post.php(29): Core\Model::getDB()
#2 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\App\Controllers\Posts.php(22): App\Models\Post::getAll()
#3 [internal function]: App\Controllers\Posts->indexAction()
#4 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Controller.php(46): call_user_func_array(Array, Array)
#5 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Router.php(120): Core\Controller->__call('index', Array)
#6 C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\public\index.php(42): Core\Router->dispatch('posts/index')
#7 {main}
Thrown in 'C:\Users\szaja\OneDrive\Pulpit\LearningPHP\BudgetApp_MVC\Core\Model.php' on line 30
